name: x2030

on:
  push:
    branches: [ master ]
    workflow_dispatch:
  schedule:
    - cron: '35 6-20 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v2


      - name: login dockerhub
        uses: docker/login-action@v1
        with:
          username: nand0p
          password: ${{ secrets.DOCKERHUB }}


      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1


      - name: dump env
        run: env

      - name: Setting value
        run: |
          pwd
          ls -la
          APP_VERSION=$(cat version.txt)
          echo "APP_VERSION=${APP_VERSION}"
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nand0p/x2030:${{ env.APP_VERSION }}
          build-args: DATE=$(date),REVISION=${{ github.sha }}


      - name: echo digest
        run: echo ${{ steps.docker_build.outputs.digest }}


      - name: run container
        run: bash -ex ./ci/run.sh daemonize


      - name: test container
        run: bash -ex ./ci/test_container.sh


      - name: test single stock
        run: bash -ex ./ci/test_single_stock.sh


      - name: test full site
        run: bash -ex ./ci/test_full_site.sh


      - name: download html
        run: wget --recursive --level 2 --no-clobber --page-requisites --adjust-extension --convert-links localhost

      - name: sed index
        run: sed -i "s/SEDME/${{ github.sha }}<br>$(date)/" localhost/index.html

      - name: release website to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: 2030.hex7.com
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'localhost'


      - name: download sub sites
        run: bash -ex ci/download_html.sh

      - name: sed index 1
        run: sed -i "s/SEDME/${{ github.sha }}<br>$(date)/" 1/index.html
      - name: sed index 2
        run: sed -i "s/SEDME/${{ github.sha }}<br>$(date)/" 2/index.html
      - name: sed index 3
        run: sed -i "s/SEDME/${{ github.sha }}<br>$(date)/" 3/index.html
      - name: sed index 4
        run: sed -i "s/SEDME/${{ github.sha }}<br>$(date)/" 4/index.html
      - name: sed index 5
        run: sed -i "s/SEDME/${{ github.sha }}<br>$(date)/" 5/index.html
      - name: sed index 6
        run: sed -i "s/SEDME/${{ github.sha }}<br>$(date)/" 6/index.html

      - name: release sub-site-1 to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: 2030.hex7.com
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '1'
          DEST_DIR: '1'

      - name: release sub-site2 to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: 2030.hex7.com
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '2'
          DEST_DIR: '2'

      - name: release sub-site-3 to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: 2030.hex7.com
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '3'
          DEST_DIR: '3'

      - name: release sub-site-4 to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: 2030.hex7.com
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '4'
          DEST_DIR: '4'


      - name: release sub-site-5 to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: 2030.hex7.com
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '5'
          DEST_DIR: '5'


      - name: release sub-site-5 to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: 2030.hex7.com
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '6'
          DEST_DIR: '6'


      - name: prepare scores for upload
        id: scores
        run: bash -ex ./ci/upload_scores.sh


      - name: upload scores to s3
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
         FILE: "${{ steps.scores.outputs.FILE_PATH }}/${{ steps.scores.outputs.FILE_NAME }}"
         AWS_REGION: 'us-east-1'
         S3_BUCKET: '2030.hex7.com'
         S3_KEY: ${{ steps.scores.outputs.FILE_NAME }}
         AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}


      - name: test website
        run: curl http://2030.hex7.com
