name: x2030

on:
  push:
    branches: [ master ]
    workflow_dispatch:
  schedule:
    - cron: '0 22 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: login dockerhub
        uses: docker/login-action@v1
        with:
          username: nand0p
          password: ${{ secrets.DOCKERHUB }}

      #- name: build container
      #  run: bash ./ci/build.sh

      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nand0p/x2030:latest
          build-args: DATE=$(date),REVISION=${{ github.sha }}

      - name: echo digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: dump env
        run: env

      - name: run container
        run: bash ./ci/run.sh daemonize

      - name: download html
        run: wget --recursive --level 2 --no-clobber --page-requisites --adjust-extension --convert-links localhost

      - name: Release Binary to S3 index
        uses: mostlytyped/s3-put-action@v1.0.0
        with:
          args: --acl-public
        env:
          LOCAL_FILE: ./localhost/*
          REMOTE_FILE: /
          AWS_BUCKET: 2030.hex7.com
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          INCLUDE_SHA256: true
